### PR TITLE
Docs/build packages

### PR DESCRIPTION
**Pull request by leostera**
Hi! Late Sunday night PR since i'm on vacation tomorrow. This is related to #27.

This PR adds:

0. `reuniverse download-packages` now pulls down package sources instead of published artefacts
1. `reuniverse extract-sources`, to extract the tarball sources
2. `reuniverse build-packages`, to compile the web packages using `bsb`
2. `reuniverse gen-docs`, to generate docs for compiled web packages using `bsdoc`
2. `reuniverse init`, that does all of the above in sequence.

### CODE REVIEW

**Comment by leostera** [comment]
As of right now the cli looks like this:

```sh
 EUNIVERSE(1)                  Reuniverse Manual                 REUNIVERSE(1)



NAME
       reuniverse - A Universal Documentation Hub for Reason

SYNOPSIS
       reuniverse COMMAND ...

COMMANDS
       build-index
           Build the Reason Package Index by scanning several sources.

       build-packages
           Build all the packages in the Reuniverse

       download-packages
           Download sources for all the packages in the Reuniverse

       extract-sources
           Extract package sources

       gen-docs
           Generate docs for built packages

       init
           Bootstrap Reuniverse

COMMON OPTIONS
       --help[=FMT] (default=auto)
           Show this help in format FMT. The value FMT must be one of `auto',
           `pager', `groff' or `plain'. With `auto', the format is `pager` or
           `plain' whenever the TERM env var is `dumb' or undefined.

       --version
           Show version information.

EXIT STATUS
       reuniverse exits with the following status:

       0   on success.

       124 on command line parsing errors.

       125 on unexpected internal errors (bugs).



Reuniverse 11VERSION11                                           REUNIVERSE(1)
```

Meaning we have subcommands for:

* building an index
* download package sources
* extracting package sources
* compiling package sources
* generating documentation

And one high-level command that those all of the above: `reuniverse init`.

**Comment by ulrikstrid** [comment]
@ostera this is a huge diff that I'm not sure I can give a good review on. I'm okay with merging this when CI passes as we're still in a early phase where we need to get things done and not nit-pick about code.

**Comment by leostera** [comment]
Good point. I think if you wanted to pick one of the commands and give some feedback on how the thing is doing the work that'd be a start.

I just want to make sure that I'm not doing anything incredibly wrong, but I expect this code to be fully rewritten ~3 months from now 🙈

**Comment by leostera** [comment]
@ulrikstrid alright, I cleaned the git history so its easier to review in the future, and the pipeline is green.

I haven't added the steps to the pipelining yet, but we can do that in a separate PR.

**Review by ulrikstrid — APPROVED** [review]
As we said on Discord, we're at a stage where we need the code to be written. I'm fine with merging this, we might be able to find some time to go through parts of it if anyone is interested in parts of it.

**Pull request merged**
